version: '3.8'

services:
  frontend:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-networks

  backend:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/amea
    depends_on:
      - mongodb
    networks:
      - mern-networks
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - mern-networks
networks:
  mern-networks:
    driver: bridge